#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Wheeler Google sign-in setup (#110, ADR 0007).
# Captured values are written to a local, gitignored env file for re-run
# defaults, then pushed to Vercel (CLI if available, dashboard paste otherwise).
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Keep captured secrets out of the repo's real .env — this file is for the
# wizard's own re-run memory only, and is gitignored. Set unconditionally: the
# library already defaulted ENV_FILE to .env above, so a `:-` default wouldn't
# take. Override with WIZARD_ENV_FILE=... if you really want somewhere else.
ENV_FILE="${WIZARD_ENV_FILE:-.wheeler-auth.env}"
VERCEL_KEYS=()   # env-var names destined for Vercel

# ask_required / ask_secret_required — like ask/ask_secret but re-prompt until
# the human actually enters something (empty required values silently break the
# OAuth setup — e.g. a blank domain yields https:///api/auth/google).
ask_required()        { while :; do ask        "$1" "$2"; [[ -n "${!1}" ]] && break; warn "Required — please enter a value."; done; }
ask_secret_required() { while :; do ask_secret "$1" "$2"; [[ -n "${!1}" ]] && break; warn "Required — please enter a value."; done; }

# vercel_env NAME VALUE — push a var to all three Vercel environments via the
# CLI (idempotent: remove-then-add). Records the name for the dashboard-paste
# fallback shown at the end when the CLI isn't available.
vercel_env() {
  local name="$1" value="$2" env pushed=0
  VERCEL_KEYS+=("$name")
  if command -v vercel >/dev/null 2>&1 && vercel whoami >/dev/null 2>&1; then
    for env in production preview development; do
      vercel env rm "$name" "$env" -y >/dev/null 2>&1 || true
      if printf '%s' "$value" | vercel env add "$name" "$env" >/dev/null 2>&1; then
        pushed=1
      fi
    done
  fi
  if (( pushed )); then
    printf '  %s✓ pushed%s %s → Vercel (production, preview, development)\n' "$GREEN" "$RESET" "$name"
  else
    SKIPPED+=("Vercel env $name — add it in the dashboard (value saved in $ENV_FILE)")
    warn "couldn't push $name via CLI — you'll paste it in the dashboard at the end"
  fi
}

banner "Wheeler Google sign-in setup"

# ── Stage 1: the deployment domain (drives the OAuth redirect URI) ─────────
stage "Your Wheeler domain"
say "Google needs the exact redirect URI your deployment uses. We'll build it"
say "from your Vercel domain (the one that serves /wheeler)."
note "e.g. hyperwheel.vercel.app  or  your custom domain"
while :; do
  ask_required WHEELER_DOMAIN "Domain (no https://, no trailing slash):"
  WHEELER_DOMAIN="${WHEELER_DOMAIN#https://}"; WHEELER_DOMAIN="${WHEELER_DOMAIN#http://}"
  WHEELER_DOMAIN="${WHEELER_DOMAIN%/}"
  [[ -n "$WHEELER_DOMAIN" ]] && break
  warn "Domain is required."
done
REDIRECT_URI="https://${WHEELER_DOMAIN}/api/auth/google"
write_env WHEELER_DOMAIN "$WHEELER_DOMAIN"
say ""
say "Your redirect URI (you'll paste this into Google in stage 3):"
printf '  %s%s%s\n' "$BOLD" "$REDIRECT_URI" "$RESET"
pause "Got it — press Enter."

# ── Stage 2: OAuth consent screen ─────────────────────────────────────────
stage "Google — OAuth consent screen"
say "Configure who can sign in. For a private tool, External + Testing is fine:"
say "only the test users you list can sign in, and there's no Google review."
open_url "https://console.cloud.google.com/apis/credentials/consent"
step "Pick (or create) a project in the top bar."
step "User type: External → Create."
step "App name: Wheeler. User support email + developer email: your email."
step "Save and continue through Scopes (add 'openid' and '.../auth/userinfo.email')."
step "On 'Test users', click + ADD USERS and add every Google account that"
step "  should be allowed to sign in (start with your own). Save."
warn "In Testing mode ONLY listed test users can sign in — that's your allow-list #1."
pause "Consent screen saved? Press Enter."

# ── Stage 3: OAuth client ID + secret ─────────────────────────────────────
stage "Google — OAuth client ID"
say "Create the Web client and register the redirect URI from stage 1."
open_url "https://console.cloud.google.com/apis/credentials"
step "+ CREATE CREDENTIALS → OAuth client ID."
step "Application type: Web application. Name: Wheeler web."
step "Under 'Authorized redirect URIs' → + ADD URI, paste EXACTLY:"
printf '  %s%s%s\n' "$BOLD" "$REDIRECT_URI" "$RESET"
step "Create. A dialog shows the Client ID and Client secret."
ask_required        GOOGLE_CLIENT_ID     "Paste the Client ID (ends .apps.googleusercontent.com):"
ask_secret_required GOOGLE_CLIENT_SECRET "Paste the Client secret:"
write_env GOOGLE_CLIENT_ID     "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"

# ── Stage 4: session secret + server allow-list ───────────────────────────
stage "Session secret + allow-list"
say "The app signs its own login cookie with a random secret (generated for you),"
say "and the server double-checks each verified email against an allow-list."
if command -v openssl >/dev/null 2>&1; then
  WHEELER_SESSION_SECRET=$(openssl rand -hex 32)
  say "Generated a 32-byte session secret."
else
  WHEELER_SESSION_SECRET=$(head -c32 /dev/urandom | od -An -tx1 | tr -d ' \n')
  warn "openssl not found — generated the secret from /dev/urandom instead."
fi
note "WHEELER_ALLOWED_EMAILS is comma-separated; must include every test user"
note "from stage 2 who should reach their trades (start with just your email)."
ask_required WHEELER_ALLOWED_EMAILS "Allowed email(s), comma-separated:"
write_env WHEELER_SESSION_SECRET "$WHEELER_SESSION_SECRET"
write_env WHEELER_ALLOWED_EMAILS "$WHEELER_ALLOWED_EMAILS"

# ── Stage 5: push everything to Vercel ────────────────────────────────────
stage "Push to Vercel"
say "Sending the four variables to your Vercel project. KV_REST_API_URL/TOKEN"
say "already exist (shared with HyperWheel); WHEELER_ENC_KEY comes later with #111."
vercel_env GOOGLE_CLIENT_ID       "$GOOGLE_CLIENT_ID"
vercel_env GOOGLE_CLIENT_SECRET   "$GOOGLE_CLIENT_SECRET"
vercel_env WHEELER_SESSION_SECRET "$WHEELER_SESSION_SECRET"
vercel_env WHEELER_ALLOWED_EMAILS "$WHEELER_ALLOWED_EMAILS"
if (( ${#SKIPPED[@]} )); then
  say ""
  warn "Vercel CLI wasn't available — add these by hand:"
  open_url "https://vercel.com/dashboard"
  step "Project → Settings → Environment Variables → add each key below"
  step "(values are saved in $ENV_FILE), scope: Production + Preview + Development."
fi
say ""
warn "After the vars are set, REDEPLOY (Vercel → Deployments → Redeploy) so the"
warn "serverless functions pick them up. Then open https://${WHEELER_DOMAIN}/wheeler"
warn "and click [ SIGN IN WITH GOOGLE ]."

finish
